# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 677b99673d368a791183ed1c7762ab070c7ab58ac509d96a311f3477d49e4805f19d520a3c11251ceee95ecc7cd02984c4359d9de0b09ae5c645845f49eaf39f

test:
  secret_key_base: 5ed607706c57f3cb4c64154de22f692e87e52daffc8f5099d677ef55974b7cdc5c66d3aa8010a33c9634ee9289670ceeb75b457c4d1c331ba5b32ba38b6e367c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
